server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
  output:
    ansi:
      enabled: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
bookshop:
  greeting: Welcome to the My BOOK catalog!

